Dashboard                     : is running
Experiment                    : has code 1725993210
Experiment                    : starts at 2024-09-10 20:33:29.686074 (729149.810054957)
Experiment                    : This experiment compares run time and resource consumption of TPC-C queries in different DBMS.
System metrics are monitored by a cluster-wide installation.
TPC-C data is generated and loaded using several threads.
Scaling factor (i.e., number of warehouses) is 16. Benchmarking runs for 2 minutes.
Benchmark is limited to DBMS PostgreSQL.
Loading is fixed to cl-worker19.
Benchmarking is fixed to cl-worker19.
SUT is fixed to cl-worker11.
Database is persisted to disk of type shared and size 30Gi.
Loading is tested with [8] threads, split into [1] pods.
Benchmarking is tested with [16] threads, split into [1, 2] pods.
Benchmarking is run as [1, 2] times the number of benchmarking pods.
Experiment is run 2 times.
Cluster monitoring            : is running
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has to wait - 2 running and 0 pending pods: max is 1 pods per cluster
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has to wait - 2 running and 0 pending pods: max is 1 pods per cluster
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has to wait - 2 running and 0 pending pods: max is 1 pods per cluster
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has to wait - 2 running and 0 pending pods: max is 1 pods per cluster
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has to wait - 2 running and 0 pending pods: max is 1 pods per cluster
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has to wait - 1 running and 0 pending pods: max is 1 pods per cluster
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has to wait - 1 running and 0 pending pods: max is 1 pods per cluster
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has to wait - 1 running and 0 pending pods: max is 1 pods per cluster
done
PostgreSQL-BHT-8-1            : will start now
PostgreSQL-BHT-8-1            : storage exists bexhoma-storage-postgresql-hammerdb-16
PostgreSQL-BHT-8-1            : loading is set to finished
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : will start benchmarking but not before 2024-09-10 18:39:30 (that is in 60 secs)
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : will start benchmarking but not before 2024-09-10 18:39:30
done
PostgreSQL-BHT-8-1            : benchmarks done 0 of 2. This will be client 1
PostgreSQL-BHT-8-1            : we will change parameters of benchmark as {'PARALLEL': '1', 'SF': '16', 'BEXHOMA_SYNCH_LOAD': 1, 'HAMMERDB_DURATION': '2', 'HAMMERDB_RAMPUP': '2', 'HAMMERDB_TYPE': 'postgresql', 'HAMMERDB_VUSERS': 16}
PostgreSQL-BHT-8-1-1-1        : start benchmarking
PostgreSQL-BHT-8-1            : benchmarking results in folder /home/perdelt/benchmarks/1725993210
- waiting 10s -               : done
PostgreSQL-BHT-8-1            : benchmarking is waiting for job bexhoma-benchmarker-postgresql-bht-8-1-1725993210-1-1-w7wtn: found
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
done
PostgreSQL-BHT-8-1            : has running benchmarks
PostgreSQL-BHT-8-1-1-1        : showing benchmarker times
PostgreSQL-BHT-8-1-1-1        : benchmarker timespan (start to end single container [s]) = 281
PostgreSQL-BHT-8-1-1-1        : benchmarker times (start/end per pod and container) = [(1725993575, 1725993847)]
PostgreSQL-BHT-8-1-1-1        : found and updated times {'benchmarker': [(1725993575, 1725993847)]}
PostgreSQL-BHT-8-1-1-1        : collecting execution metrics of SUT
PostgreSQL-BHT-8-1-1-1        : collecting metrics of benchmarker
done
PostgreSQL-BHT-8-1            : benchmarks done 0 of 2. This will be client 2
PostgreSQL-BHT-8-1            : we will change parameters of benchmark as {'PARALLEL': '2', 'SF': '16', 'BEXHOMA_SYNCH_LOAD': 1, 'HAMMERDB_DURATION': '2', 'HAMMERDB_RAMPUP': '2', 'HAMMERDB_TYPE': 'postgresql', 'HAMMERDB_VUSERS': 16}
PostgreSQL-BHT-8-1-1-2        : start benchmarking
PostgreSQL-BHT-8-1            : benchmarking results in folder /home/perdelt/benchmarks/1725993210
- waiting 10s -               : done
PostgreSQL-BHT-8-1            : benchmarking is waiting for job bexhoma-benchmarker-postgresql-bht-8-1-1725993210-1-2-2cvth: found
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
done
PostgreSQL-BHT-8-1            : has running benchmarks
PostgreSQL-BHT-8-1-1-2        : showing benchmarker times
PostgreSQL-BHT-8-1-1-2        : benchmarker timespan (start to end single container [s]) = 282
PostgreSQL-BHT-8-1-1-2        : benchmarker times (start/end per pod and container) = [(1725993900, 1725994166), (1725993900, 1725994166)]
PostgreSQL-BHT-8-1-1-2        : found and updated times {'benchmarker': [(1725993900, 1725994166), (1725993900, 1725994166)]}
PostgreSQL-BHT-8-1-1-2        : collecting execution metrics of SUT
PostgreSQL-BHT-8-1-1-2        : collecting metrics of benchmarker
done
PostgreSQL-BHT-8-1            : benchmarks done 0 of 2. This will be client 3
PostgreSQL-BHT-8-1            : we will change parameters of benchmark as {'PARALLEL': '2', 'SF': '16', 'BEXHOMA_SYNCH_LOAD': 1, 'HAMMERDB_DURATION': '2', 'HAMMERDB_RAMPUP': '2', 'HAMMERDB_TYPE': 'postgresql', 'HAMMERDB_VUSERS': 8}
PostgreSQL-BHT-8-1-1-3        : start benchmarking
PostgreSQL-BHT-8-1            : benchmarking results in folder /home/perdelt/benchmarks/1725993210
- waiting 10s -               : done
PostgreSQL-BHT-8-1            : benchmarking is waiting for job bexhoma-benchmarker-postgresql-bht-8-1-1725993210-1-3-bqdl5: found
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
done
PostgreSQL-BHT-8-1            : has running benchmarks
PostgreSQL-BHT-8-1-1-3        : showing benchmarker times
PostgreSQL-BHT-8-1-1-3        : benchmarker timespan (start to end single container [s]) = 282
PostgreSQL-BHT-8-1-1-3        : benchmarker times (start/end per pod and container) = [(1725994225, 1725994492), (1725994226, 1725994481)]
PostgreSQL-BHT-8-1-1-3        : found and updated times {'benchmarker': [(1725994225, 1725994492), (1725994226, 1725994481)]}
PostgreSQL-BHT-8-1-1-3        : collecting execution metrics of SUT
PostgreSQL-BHT-8-1-1-3        : collecting metrics of benchmarker
done
PostgreSQL-BHT-8-1            : benchmarks done 0 of 2. This will be client 4
PostgreSQL-BHT-8-1            : we will change parameters of benchmark as {'PARALLEL': '4', 'SF': '16', 'BEXHOMA_SYNCH_LOAD': 1, 'HAMMERDB_DURATION': '2', 'HAMMERDB_RAMPUP': '2', 'HAMMERDB_TYPE': 'postgresql', 'HAMMERDB_VUSERS': 8}
PostgreSQL-BHT-8-1-1-4        : start benchmarking
PostgreSQL-BHT-8-1            : benchmarking results in folder /home/perdelt/benchmarks/1725993210
- waiting 10s -               : done
PostgreSQL-BHT-8-1            : benchmarking is waiting for job bexhoma-benchmarker-postgresql-bht-8-1-1725993210-1-4-jhhmf: found
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
done
PostgreSQL-BHT-8-1            : has running benchmarks
PostgreSQL-BHT-8-1-1-4        : showing benchmarker times
PostgreSQL-BHT-8-1-1-4        : benchmarker timespan (start to end single container [s]) = 313
PostgreSQL-BHT-8-1-1-4        : benchmarker times (start/end per pod and container) = [(1725994550, 1725994832), (1725994553, 1725994836), (1725994551, 1725994831), (1725994552, 1725994833)]
PostgreSQL-BHT-8-1-1-4        : found and updated times {'benchmarker': [(1725994550, 1725994832), (1725994553, 1725994836), (1725994551, 1725994831), (1725994552, 1725994833)]}
PostgreSQL-BHT-8-1-1-4        : collecting execution metrics of SUT
PostgreSQL-BHT-8-1-1-4        : collecting metrics of benchmarker
done
PostgreSQL-BHT-8-1            : can be stopped
PostgreSQL-BHT-8-1            : still being removed
done
PostgreSQL-BHT-8-1            : starts again
PostgreSQL-BHT-8-1            : storage exists bexhoma-storage-postgresql-hammerdb-16
PostgreSQL-BHT-8-1            : loading is set to finished
- waiting 10s -               : done
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : will start benchmarking but not before 2024-09-10 19:03:53 (that is in 60 secs)
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : will start benchmarking but not before 2024-09-10 19:03:53
done
PostgreSQL-BHT-8-1            : benchmarks done 1 of 2. This will be client 1
PostgreSQL-BHT-8-1            : we will change parameters of benchmark as {'PARALLEL': '1', 'SF': '16', 'BEXHOMA_SYNCH_LOAD': 1, 'HAMMERDB_DURATION': '2', 'HAMMERDB_RAMPUP': '2', 'HAMMERDB_TYPE': 'postgresql', 'HAMMERDB_VUSERS': 16}
PostgreSQL-BHT-8-1-2-1        : start benchmarking
PostgreSQL-BHT-8-1            : benchmarking results in folder /home/perdelt/benchmarks/1725993210
- waiting 10s -               : done
PostgreSQL-BHT-8-1            : benchmarking is waiting for job bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-1-89swf: found
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
done
PostgreSQL-BHT-8-1            : has running benchmarks
PostgreSQL-BHT-8-1-2-1        : showing benchmarker times
PostgreSQL-BHT-8-1-2-1        : benchmarker timespan (start to end single container [s]) = 282
PostgreSQL-BHT-8-1-2-1        : benchmarker times (start/end per pod and container) = [(1725995038, 1725995313)]
PostgreSQL-BHT-8-1-2-1        : found and updated times {'benchmarker': [(1725995038, 1725995313)]}
PostgreSQL-BHT-8-1-2-1        : collecting execution metrics of SUT
PostgreSQL-BHT-8-1-2-1        : collecting metrics of benchmarker
done
PostgreSQL-BHT-8-1            : benchmarks done 1 of 2. This will be client 2
PostgreSQL-BHT-8-1            : we will change parameters of benchmark as {'PARALLEL': '2', 'SF': '16', 'BEXHOMA_SYNCH_LOAD': 1, 'HAMMERDB_DURATION': '2', 'HAMMERDB_RAMPUP': '2', 'HAMMERDB_TYPE': 'postgresql', 'HAMMERDB_VUSERS': 16}
PostgreSQL-BHT-8-1-2-2        : start benchmarking
PostgreSQL-BHT-8-1            : benchmarking results in folder /home/perdelt/benchmarks/1725993210
- waiting 10s -               : done
PostgreSQL-BHT-8-1            : benchmarking is waiting for job bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-2-lwnpd: found
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
done
PostgreSQL-BHT-8-1            : has running benchmarks
PostgreSQL-BHT-8-1-2-2        : showing benchmarker times
PostgreSQL-BHT-8-1-2-2        : benchmarker timespan (start to end single container [s]) = 282
PostgreSQL-BHT-8-1-2-2        : benchmarker times (start/end per pod and container) = [(1725995363, 1725995631), (1725995363, 1725995633)]
PostgreSQL-BHT-8-1-2-2        : found and updated times {'benchmarker': [(1725995363, 1725995631), (1725995363, 1725995633)]}
PostgreSQL-BHT-8-1-2-2        : collecting execution metrics of SUT
PostgreSQL-BHT-8-1-2-2        : collecting metrics of benchmarker
done
PostgreSQL-BHT-8-1            : benchmarks done 1 of 2. This will be client 3
PostgreSQL-BHT-8-1            : we will change parameters of benchmark as {'PARALLEL': '2', 'SF': '16', 'BEXHOMA_SYNCH_LOAD': 1, 'HAMMERDB_DURATION': '2', 'HAMMERDB_RAMPUP': '2', 'HAMMERDB_TYPE': 'postgresql', 'HAMMERDB_VUSERS': 8}
PostgreSQL-BHT-8-1-2-3        : start benchmarking
PostgreSQL-BHT-8-1            : benchmarking results in folder /home/perdelt/benchmarks/1725993210
- waiting 10s -               : done
PostgreSQL-BHT-8-1            : benchmarking is waiting for job bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-3-5d6ks: found
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
- waiting 30s -               : done
PostgreSQL-BHT-8-1            : has running benchmarks
done
PostgreSQL-BHT-8-1            : has running benchmarks
PostgreSQL-BHT-8-1-2-3        : showing benchmarker times
PostgreSQL-BHT-8-1-2-3        : benchmarker timespan (start to end single container [s]) = 282
PostgreSQL-BHT-8-1-2-3        : benchmarker times (start/end per pod and container) = [(1725995689, 1725995961), (1725995689, 1725995953)]
PostgreSQL-BHT-8-1-2-3        : found and updated times {'benchmarker': [(1725995689, 1725995961), (1725995689, 1725995953)]}
PostgreSQL-BHT-8-1-2-3        : collecting execution metrics of SUT
PostgreSQL-BHT-8-1-2-3        : collecting metrics of benchmarker
done
PostgreSQL-BHT-8-1            : benchmarks done 1 of 2. This will be client 4
PostgreSQL-BHT-8-1            : we will change parameters of benchmark as {'PARALLEL': '4', 'SF': '16', 'BEXHOMA_SYNCH_LOAD': 1, 'HAMMERDB_DURATION': '2', 'HAMMERDB_RAMPUP': '2', 'HAMMERDB_TYPE': 'postgresql', 'HAMMERDB_VUSERS': 8}
PostgreSQL-BHT-8-1-2-4        : start benchmarking
PostgreSQL-BHT-8-1            : benchmarking results in folder /home/perdelt/benchmarks/1725993210
- waiting 10s -               : done
PostgreSQL-BHT-8-1            : benchmarking is waiting for job bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7: found
done
PostgreSQL-BHT-8-1            : has running benchmarks
PostgreSQL-BHT-8-1-2-4        : showing benchmarker times
PostgreSQL-BHT-8-1-2-4        : benchmarker timespan (start to end single container [s]) = 42
PostgreSQL-BHT-8-1-2-4        : benchmarker times (start/end per pod and container) = [(1725996015, 1725996041), (1725996016, 1725996042), (1725996016, 1725996040), (1725996014, 1725996044)]
PostgreSQL-BHT-8-1-2-4        : found and updated times {'benchmarker': [(1725996015, 1725996041), (1725996016, 1725996042), (1725996016, 1725996040), (1725996014, 1725996044)]}
PostgreSQL-BHT-8-1-2-4        : collecting execution metrics of SUT
PostgreSQL-BHT-8-1-2-4        : collecting metrics of benchmarker
done
PostgreSQL-BHT-8-1            : can be stopped
Experiment ends at 2024-09-10 21:21:34.452159 (732034.576138583): 2884.76608362596s total
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-gfqdf.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-662k7.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-vbdd6.dbmsbenchmarker.log
/home/perdelt/benchmarks/1725993210/bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log something went wrong
Length mismatch: Expected axis has 0 elements, new values have 17 elements
Traceback (most recent call last):
  File "/home/perdelt/repositories/Benchmark-Experiment-Host-Manager/bexhoma/evaluators.py", line 1106, in log_to_df
    df.columns = ['connection', 'configuration', 'experiment_run', 'client', 'pod', 'pod_count', 'iterations', 'duration', 'rampup', 'sf', 'run', 'errors', 'vusers_loading', 'vusers', 'NOPM', 'TPM', 'dbms']
    ^^^^^^^^^^
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/perdelt/anaconda3/envs/dbmsbenchmarker/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 17 elements

Error in bexhoma-benchmarker-postgresql-bht-8-1-1725993210-2-4-99hs8.dbmsbenchmarker.log
bexhoma-dashboard-9b85f945f-rp8sq Running
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-2-2                          ...            
0                       PostgreSQL-BHT-8-1-2-2  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-2-2
['16']
vusers 16
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-2-2                          ...            
0                       PostgreSQL-BHT-8-1-2-2  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-2-2
['16']
vusers 16
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-2                          ...            
0                       PostgreSQL-BHT-8-1-1-2  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-2
['16']
vusers 16
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-2                          ...            
0                       PostgreSQL-BHT-8-1-1-2  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-2
['16']
vusers 16
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-3                          ...            
0                       PostgreSQL-BHT-8-1-1-3  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-3
['8']
vusers 8
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-4                          ...            
0                       PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-4
['8']
vusers 8
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-2-1                          ...            
0                       PostgreSQL-BHT-8-1-2-1  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-2-1
['16']
vusers 16
                                      connection  ...        dbms
connection_pod                                    ...            
PostgreSQL-BHT-8-1-2-2-1  PostgreSQL-BHT-8-1-2-2  ...  PostgreSQL
PostgreSQL-BHT-8-1-2-2-2  PostgreSQL-BHT-8-1-2-2  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-2-1  PostgreSQL-BHT-8-1-1-2  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-2-2  PostgreSQL-BHT-8-1-1-2  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-3-1  PostgreSQL-BHT-8-1-1-3  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-4-1  PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL
PostgreSQL-BHT-8-1-2-1-1  PostgreSQL-BHT-8-1-2-1  ...  PostgreSQL
PostgreSQL-BHT-8-1-2-3-1  PostgreSQL-BHT-8-1-2-3  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-1-1  PostgreSQL-BHT-8-1-1-1  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-3-2  PostgreSQL-BHT-8-1-1-3  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-4-2  PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-4-3  PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL
PostgreSQL-BHT-8-1-2-3-2  PostgreSQL-BHT-8-1-2-3  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-4-4  PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL

[14 rows x 17 columns]
connection_pod
['16', '16', '16', '16', '8', '8', '16', '8', '16', '8', '8', '8', '8', '8']
vusers 16 16 16 16 8 8 16 8 16 8 8 8 8 8
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-2-3                          ...            
0                       PostgreSQL-BHT-8-1-2-3  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-2-3
['8']
vusers 8
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-1                          ...            
0                       PostgreSQL-BHT-8-1-1-1  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-1
['16']
vusers 16
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-3                          ...            
0                       PostgreSQL-BHT-8-1-1-3  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-3
['8']
vusers 8
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-4                          ...            
0                       PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-4
['8']
vusers 8
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-4                          ...            
0                       PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-4
['8']
vusers 8
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-2-3                          ...            
0                       PostgreSQL-BHT-8-1-2-3  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-2-3
['8']
vusers 8
                                    connection  ...        dbms
PostgreSQL-BHT-8-1-1-4                          ...            
0                       PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL

[1 rows x 17 columns]
PostgreSQL-BHT-8-1-1-4
['8']
vusers 8
Benchmarking                                       connection  ...        dbms
connection_pod                                    ...            
PostgreSQL-BHT-8-1-2-2-1  PostgreSQL-BHT-8-1-2-2  ...  PostgreSQL
PostgreSQL-BHT-8-1-2-2-2  PostgreSQL-BHT-8-1-2-2  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-2-1  PostgreSQL-BHT-8-1-1-2  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-2-2  PostgreSQL-BHT-8-1-1-2  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-3-1  PostgreSQL-BHT-8-1-1-3  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-4-1  PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL
PostgreSQL-BHT-8-1-2-1-1  PostgreSQL-BHT-8-1-2-1  ...  PostgreSQL
PostgreSQL-BHT-8-1-2-3-1  PostgreSQL-BHT-8-1-2-3  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-1-1  PostgreSQL-BHT-8-1-1-1  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-3-2  PostgreSQL-BHT-8-1-1-3  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-4-2  PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-4-3  PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL
PostgreSQL-BHT-8-1-2-3-2  PostgreSQL-BHT-8-1-2-3  ...  PostgreSQL
PostgreSQL-BHT-8-1-1-4-4  PostgreSQL-BHT-8-1-1-4  ...  PostgreSQL

[14 rows x 17 columns]
Workflow {'PostgreSQL-BHT-8-1': [[2, 1, 2], [2, 2, 4, 1]]}
Result workflow not complete

## Show Summary

### Workload
    HammerDB Workload SF=16 (warehouses for TPC-C)
    This includes no queries. HammerDB runs the benchmark
    This experiment compares run time and resource consumption of TPC-C queries in different DBMS.
System metrics are monitored by a cluster-wide installation.
TPC-C data is generated and loaded using several threads.
Scaling factor (i.e., number of warehouses) is 16. Benchmarking runs for 2 minutes.
Benchmark is limited to DBMS PostgreSQL.
Loading is fixed to cl-worker19.
Benchmarking is fixed to cl-worker19.
SUT is fixed to cl-worker11.
Database is persisted to disk of type shared and size 30Gi.
Loading is tested with [8] threads, split into [1] pods.
Benchmarking is tested with [16] threads, split into [1, 2] pods.
Benchmarking is run as [1, 2] times the number of benchmarking pods.
Experiment is run 2 times.

### Connections
PostgreSQL-BHT-8-1-1-1 uses docker image postgres:16.1
    RAM:541008605184
    CPU:AMD Opteron(tm) Processor 6378
    Cores:64
    host:5.15.0-116-generic
    node:cl-worker11
    disk:246349732
    datadisk:4294945
    volume_size:30G
    volume_used:4.1G
    requests_cpu:4
    requests_memory:16Gi
PostgreSQL-BHT-8-1-1-2 uses docker image postgres:16.1
    RAM:541008605184
    CPU:AMD Opteron(tm) Processor 6378
    Cores:64
    host:5.15.0-116-generic
    node:cl-worker11
    disk:246349732
    datadisk:4401613
    volume_size:30G
    volume_used:4.2G
    requests_cpu:4
    requests_memory:16Gi
PostgreSQL-BHT-8-1-1-3 uses docker image postgres:16.1
    RAM:541008605184
    CPU:AMD Opteron(tm) Processor 6378
    Cores:64
    host:5.15.0-116-generic
    node:cl-worker11
    disk:246349732
    datadisk:4527693
    volume_size:30G
    volume_used:4.2G
    requests_cpu:4
    requests_memory:16Gi
PostgreSQL-BHT-8-1-1-4 uses docker image postgres:16.1
    RAM:541008605184
    CPU:AMD Opteron(tm) Processor 6378
    Cores:64
    host:5.15.0-116-generic
    node:cl-worker11
    disk:246349732
    datadisk:4611997
    volume_size:30G
    volume_used:4.4G
    requests_cpu:4
    requests_memory:16Gi
PostgreSQL-BHT-8-1-2-1 uses docker image postgres:16.1
    RAM:541008605184
    CPU:AMD Opteron(tm) Processor 6378
    Cores:64
    host:5.15.0-116-generic
    node:cl-worker11
    disk:248309504
    datadisk:4717273
    volume_size:30G
    volume_used:4.5G
    requests_cpu:4
    requests_memory:16Gi
PostgreSQL-BHT-8-1-2-2 uses docker image postgres:16.1
    RAM:541008605184
    CPU:AMD Opteron(tm) Processor 6378
    Cores:64
    host:5.15.0-116-generic
    node:cl-worker11
    disk:246349900
    datadisk:4797477
    volume_size:30G
    volume_used:4.5G
    requests_cpu:4
    requests_memory:16Gi
PostgreSQL-BHT-8-1-2-3 uses docker image postgres:16.1
    RAM:541008605184
    CPU:AMD Opteron(tm) Processor 6378
    Cores:64
    host:5.15.0-116-generic
    node:cl-worker11
    disk:246349900
    datadisk:4897773
    volume_size:30G
    volume_used:4.5G
    requests_cpu:4
    requests_memory:16Gi
PostgreSQL-BHT-8-1-2-4 uses docker image postgres:16.1
    RAM:541008605184
    CPU:AMD Opteron(tm) Processor 6378
    Cores:64
    host:5.15.0-116-generic
    node:cl-worker11
    disk:246349900
    datadisk:4983101
    volume_size:30G
    volume_used:4.5G
    requests_cpu:4
    requests_memory:16Gi

### Execution
                        experiment_run  vusers  client  pod_count      NOPM       TPM  duration  errors
PostgreSQL-BHT-8-1-1-1               1      16       1          1  11054.00  34049.00         2       0
PostgreSQL-BHT-8-1-1-2               1      32       2          2  11097.00  31949.00         2       0
PostgreSQL-BHT-8-1-1-3               1      16       3          2   8856.50  28298.50         2       0
PostgreSQL-BHT-8-1-1-4               1      32       4          4   9957.25  28916.25         2       0
PostgreSQL-BHT-8-1-2-1               2      16       1          1   9245.00  30188.00         2       0
PostgreSQL-BHT-8-1-2-2               2      32       2          2  10132.00  30407.00         2       0
PostgreSQL-BHT-8-1-2-3               2      16       3          2   8986.50  28825.00         2       0

Warehouses: 16

### Workflow
DBMS PostgreSQL-BHT-8-1 - Pods [[2, 1, 2], [2, 2, 4, 1]]

### Loading
                        time_load  terminals  pods  Imported warehouses [1/h]
PostgreSQL-BHT-8-1-1-1      105.0        1.0   1.0                 548.571429
PostgreSQL-BHT-8-1-1-2      105.0        1.0   2.0                 548.571429
PostgreSQL-BHT-8-1-1-3      105.0        1.0   2.0                 548.571429
PostgreSQL-BHT-8-1-1-4      105.0        1.0   4.0                 548.571429
PostgreSQL-BHT-8-1-2-1      105.0        1.0   1.0                 548.571429
PostgreSQL-BHT-8-1-2-2      105.0        1.0   2.0                 548.571429
PostgreSQL-BHT-8-1-2-3      105.0        1.0   2.0                 548.571429
PostgreSQL-BHT-8-1-2-4      105.0        1.0   4.0                 548.571429

### Execution - SUT
                        CPU [CPUs]  Max CPU  Max RAM [Gb]  Max RAM Cached [Gb]
PostgreSQL-BHT-8-1-1-1    14181.81    62.81          4.99                 7.14
PostgreSQL-BHT-8-1-1-2    14824.60    63.63          5.47                 7.74
PostgreSQL-BHT-8-1-1-3    15411.30    33.44          5.44                 7.78
PostgreSQL-BHT-8-1-1-4    16935.32    63.60          6.02                 8.46
PostgreSQL-BHT-8-1-2-1    62425.80    62.90          9.32                14.30
PostgreSQL-BHT-8-1-2-2    15916.39    63.63          5.92                 8.50
PostgreSQL-BHT-8-1-2-3    15150.28    62.90          5.56                 8.21
PostgreSQL-BHT-8-1-2-4        0.00     0.00          4.46                 7.14

### Execution - Benchmarker
                        CPU [CPUs]  Max CPU  Max RAM [Gb]  Max RAM Cached [Gb]
PostgreSQL-BHT-8-1-1-1       23.05     0.10          0.06                 0.06
PostgreSQL-BHT-8-1-1-2       20.12     0.05          0.16                 0.16
PostgreSQL-BHT-8-1-1-3       24.55     0.08          0.18                 0.18
PostgreSQL-BHT-8-1-1-4       18.31     0.07          0.20                 0.20
PostgreSQL-BHT-8-1-2-1       20.29     0.08          0.13                 0.13
PostgreSQL-BHT-8-1-2-2       20.16     0.10          0.16                 0.16
PostgreSQL-BHT-8-1-2-3       25.59     0.08          0.18                 0.18
PostgreSQL-BHT-8-1-2-4        0.00     0.00          0.07                 0.07
TEST passed: NOPM contains no 0 or NaN
